#!/bin/bash

# Copyright 2017, Backblaze Inc. All Rights Reserved.
# License https://www.backblaze.com/using_b2_code.html

cd $BZ_TREE_TRUNK/prototype/b2sdk4j/src

PACKAGES=com.backblaze.b2.client
#SRCS=com/backblaze/json/BzJson.java

javadoc $PACKAGES $SRCS -public -d /tmp/b2sdk4j_docs

